name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  rubocop:
    name: RuboCop Action
    runs-on: ubuntu-latest
    timeout-minutes: 2
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Rubocop Linter Action
      - uses: andrewmcodes/rubocop-linter-action@v3.2.0
