name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  rubocop:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    - name: Rubocop Linter Action
      uses: andrewmcodes/rubocop-linter-action@v3.2.0

