name: Rubocop

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: rubocop
        uses: Freshly/Octocop@v0.0.1
        with:
          github_token: ${{ secrets.github_token }}
          rubocop_version: 0.74
          reporter: github-pr-check
          additional_gems: 'spicerack-styleguide'
          rubocop_flags: '-c .rubocop.yml'
